name: Build

on:
  pull_request:
  push:

jobs:
  build:
    name: Build 🚀
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup-go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: false

      - name: build
        run: go build
      
      - name: Summarize
        run: chmod +x ./tftools & ./tftools summarize --compact --show-tags <demo.json