name: GoSec 🛠️
on:
  pull_request:
  push:
    #    tags:
    #      - '*'
    branches:
      - '*'

permissions:
  contents: write

jobs:
  build:
    name: Go build 🚀
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup-go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: false

      - name: security
        uses: securego/gosec@master
        with:
          args: -exclude=G104,G204,G107 ./...
