# There are not tests, but... just prepare the pipeline for the future
name: Test
on:
  pull_request:
  push:

jobs:
  test:
    name: Test 🚀
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup-go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: false

      - name: test
        run: go test -v ./...
